service: serverless-auth-boilerplate

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "dynamodb:*"
       Resource:
         - "*"

plugins:
 - serverless-async-await
 - serverless-plugin-warmup

functions:

  login:
    warmup: true
    memorySize: 512
    timeout: 10
    handler: src/route/auth.login
    events:
      - http:
          method: POST
          path: /auth/login
          cors: true

  register:
    warmup: true
    memorySize: 512
    timeout: 10
    handler: src/route/auth.register
    events:
      - http:
          method: POST
          path: /auth/register
          cors: true

  validate:
    warmup: true
    memorySize: 512
    timeout: 10
    handler: src/route/auth.validate
    events:
      - http:
          method: POST
          path: /auth/validate
          cors: true

  resendValidate:
    warmup: true
    memorySize: 512
    timeout: 10
    handler: src/route/auth.resendValidate
    events:
      - http:
          method: POST
          path: /auth/resend-validate
          cors: true

  forgotPassword:
    warmup: true
    memorySize: 512
    timeout: 10
    handler: src/route/auth.forgotPassword
    events:
      - http:
          method: POST
          path: /auth/forgot-password
          cors: true

  resetPassword:
    warmup: true
    memorySize: 512
    timeout: 10
    handler: src/route/auth.resetPassword
    events:
      - http:
          method: POST
          path: /auth/reset-password
          cors: true
