service: serverless-auth-boilerplate

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "dynamodb:*"
       Resource:
         - "*"

plugins:
 - serverless-async-await
 - serverless-plugin-warmup

functions:

  login:
    warmup: true
    memorySize: 512
    timeout: 3
    handler: src/route/auth.login
    events:
      - http:
          method: POST
          path: /auth/login
          cors: true

  register:
    warmup: true
    memorySize: 512
    timeout: 3
    handler: src/route/auth.register
    events:
      - http:
          method: POST
          path: /auth/register
          cors: true

  forgorPassword:
    warmup: true
    memorySize: 512
    timeout: 3
    handler: src/route/auth.forgorPassword
    events:
      - http:
          method: POST
          path: /auth/forgot-password
          cors: true
